### ISSUE TITLE
empire-web fails to log in to Empire rest-api 

### ISSUE THREAD

**Issue by thesle3p** [interference-security/empire-web#5]
Hi, it looks like Empire changed the way it's API authenticates (Requires a API token), any chance you can update empire-web to work with the new authentication scheme?

**Comment by interference-security** [comment]
Thanks for raising this issue. After checking it, I have found that it is because of REST API authentication bug in PowerShell Empire. A pull request has been filed (https://github.com/PowerShellEmpire/Empire/pull/329).

After fixing the code in PowerShell Empire you should be able to authenticate and use Empire Web. Please let us know if it solves the problem.
