### ISSUE TITLE
unable to login

### ISSUE THREAD

**Issue by theoneandonly-vector** [interference-security/empire-web#7]
The 127.0.0.1 page isn’t working

127.0.0.1 is currently unable to handle this request.
HTTP ERROR 500

**Comment by theoneandonly-vector** [comment]
after submit of the login-form

**Comment by interference-security** [comment]
Thanks for raising the issue. It seems to be an issue with your setup. Please make sure the requirements are satisfied: https://github.com/interference-security/empire-web#requirements

**Comment by theoneandonly-vector** [comment]
is it a problem, if I use php7 instead of 5?

root@Debian:~# php -i | grep -i curl
/etc/php/7.0/cli/conf.d/20-curl.ini,
curl
cURL support => enabled
cURL Information => 7.50.1

**Comment by theoneandonly-vector** [comment]
a reboot fixed the issue.. 
BUT I still can't login.

" Failed login attempt."
I think it's a problem with passwords (EmpireGUI has the same problem, but they somehow wrote a workaround. -> https://github.com/tristandostaler/EmpireGUI

so could you add a API-token-authentification instead?

**Comment by interference-security** [comment]
Failed login attempt is because of REST API authentication bug in PowerShell Empire. A pull request had been raised: https://github.com/adaptivethreat/Empire/pull/329.

After fixing the code in PowerShell Empire you should be able to authenticate and use Empire Web. Please let us know if it solves the issue.
Refer: https://github.com/adaptivethreat/Empire/pull/329/commits/9bbcb0d7ce11adfad7ae500d63e91b9950d74150

**Comment by theoneandonly-vector** [comment]
thx, it's fixed, merging in the official branch would be great..
